### ISSUE TITLE
AWS-issued certificate

### ISSUE THREAD

**Issue by Opalo** [docker-mailserver/docker-mailserver-helm#1]
Hi!

Is it possible to not to use cert-manager and instead use a AWS-issued (via cert manager) certificate?

**Comment by funkypenguin** [comment]
Hey @Opalo!

Certainly it's possible, it'd just be a matter of configuring cert-manager independently, to use the AWS-issued cert instead. Sorry it's taken so long to respond here, if you're still interested, I'm happy to help :)

D

**Comment by cfis** [comment]
Yes. See the `certificate` key. https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#certificate
