### ISSUE TITLE
Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by emouawad** [docker-mailserver/docker-mailserver-helm#103]
The chart is adding label to ServiceMonitor
release: [release-name] 
there is no way to add an additional label.

My kube-prometheus-stack setup requires a label on the ServiceMonitor
release: kube-prom-stack

Would it be possible for the chart to add an additionalLabels:  feature ?

**Comment by cfis** [comment]
Sure. Can you create a PR?

**Comment by emouawad** [comment]
i am afraid currently my skillset doesn't include yet templating with helm

**Comment by emouawad** [comment]
Hi, please don't get me wrong - i really appreciate the effort and time you guys put in helping the dev community.

but this PR doesn't solve the previously described issue: the issue is on the ServiceMonitor not on the Deployment.
While this could help somebody else it doesn't solve the requirement for kube-prometheus-stack multi release installs: to differentiate multiple prometheus installs running on the same cluster. The differentiation is done on the label release: exactly as follows:
A) release: kube-prom-stack
B) release: kube-prom-stack2

Bitnami charts and others enable usually on the ServiceMonitor an additionalLabels property
Example: 
https://artifacthub.io/packages/helm/bitnami/redis?modal=template&template=servicemonitor.yaml - Line 13
https://artifacthub.io/packages/helm/bitnami/redis?modal=values&path=metrics.serviceMonitor.additionalLabels

**Comment by cfis** [comment]
Yeah ok, reopening. Just need to do the same thing for service monitor.

**Comment by cfis** [comment]
Ok - see https://github.com/docker-mailserver/docker-mailserver-helm/pull/110. Hopefully that does the trick.
