### ISSUE TITLE
Readiness and Liveness probes constantly failing

### ISSUE THREAD

**Issue by radicand** [docker-mailserver/docker-mailserver-helm#134]
On my installation, the probes mechanism isn't working well - the command is often hanging (I can replicate this in a bash exec). However, the command can also be simplified greatly by just feeding a list of the services to verify to the `supervisorctl status` command instead.

I developed this change in a branch and tested it -- https://github.com/docker-mailserver/docker-mailserver-helm/compare/master...radicand:docker-mailserver-helm:fix/probes?expand=1 -- however, before submitting a pull request for a cleaned up version of this, I wanted to check to see if any other users are also noticing the probes failing or if it's just me. You can check your deployed pod and see if the restarts are non-zero and if k8s is reporting a command timeout as the probe restart cause.

**Comment by cfis** [comment]
Hmm, not seeing restarts or failed liveness probes on my end. In your changes:

`supervisorctl status | grep -E "mailserver|postfix" | grep RUNNING`

To:

`- supervisorctl status mailserver postfix`

Don't you still need to the `grep RUNNING` check?

**Comment by radicand** [comment]
No, the command only returns a 0 exit code if the services specified are in the running state.  Anything else is nonzero and results in probe failure.

**Comment by cfis** [comment]
Ah I see. Anyway, this does seem cleaner, happy to merge a PR.
