### ISSUE TITLE
Log to stdout only

### ISSUE THREAD

**Issue by sdlAnti** [docker-mailserver/docker-mailserver-helm#139]
Hello!
I collect pod logs using loki stack.  
How can I disable logging to files in /var/log/mail/ and leave only stdout?

**Comment by cfis** [comment]
There is nothing specific in the Helm chart.

You'll want to disable postfix logging - maybe this link helps - https://betterstack.com/community/guides/logging/how-to-start-logging-with-postfix/

However, that setup is controlled by the docker-mailserver project which builds the container this helm chart runs. So you'll probably want to ask in that project. If there is a knob that it exposes, then we can surface that in the helm chart. If that's the case, then reopen this ticket.
