### ISSUE TITLE
Certificate.spec with deprecated "acme" field

### ISSUE THREAD

**Issue by tomaszn** [docker-mailserver/docker-mailserver-helm#2]
Installing on a fresh cluster with cert-manager 0.14.1:
> $ helm install funkypenguin/docker-mailserver --generate-name
> 
> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Certificate.spec): unknown field "acme" in io.cert-manager.v1alpha2.Certificate.spec

In v0.11 cert-manager removed fields deprecated in v0.8 (certificate.spec.acme, issuer.spec.http01 and issuer.spec.dns01), see [release notes](https://cert-manager.io/docs/release-notes/release-notes-0.11/).

**Comment by funkypenguin** [comment]
Aah, I'd not noticed this since I've deployed it to a cluster which uses a "global" wildcard cert and secret-replicator to copy the cert between namespaces. Are you deploying this in a way in which the only app using cert-manager would be docker-mailserver?

**Comment by tomaszn** [comment]
I will add more apps later. Not sure if that matters, but my cluster consists of a single k3s node with traefik.

**Comment by abh** [comment]
fwiw I ran into this, too. My cert-manager is pretty much exactly just following the default cert-manager installation documentation, I believe.

**Comment by bklang** [comment]
I was able to fix this by making the following change:

```diff
diff --git a/charts/docker-mailserver/templates/certificate-crd.yaml b/charts/docker-mailserver/templates/certificate-crd.yaml
index 2f524e2..f95bc18 100644
--- a/charts/docker-mailserver/templates/certificate-crd.yaml
+++ b/charts/docker-mailserver/templates/certificate-crd.yaml
@@ -1,6 +1,6 @@
 {{- if not .Values.ssl.useExisting -}}
 ---
-apiVersion: cert-manager.io/v1alpha2
+apiVersion: certmanager.k8s.io/v1alpha1
 kind: Certificate
 metadata:
   name: {{ template "dockermailserver.fullname" . }}-tls
```

**Comment by funkypenguin** [comment]
Unless I'm reading that backwards, you're _reintroducing_ the [deprecated API](https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/) which was removed in cert-manager v0.11?

**Comment by bklang** [comment]
> Unless I'm reading that backwards, you're _reintroducing_ the [deprecated API](https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/) which was removed in cert-manager v0.11?

Yep, you're right. It appears that our K8s cluster is running an older version of cert-manager. Perhaps the original reporter of this issue is in a similar situation.

**Comment by bklang** [comment]
And then just realized that the original comment mentioned cert-manager 0.14, so I have no idea. All I can say is that it worked for me 🤷‍♂️

**Comment by cfis** [comment]
cert-manager has been removed from the chart. So closing this issue.
