### ISSUE TITLE
fail2ban toggle is inconsistent

### ISSUE THREAD

**Issue by abh** [docker-mailserver/docker-mailserver-helm#26]
It's weird that the fail2ban toggle is true/false when most of the other settings are 1/0.

I know that the 1/0's are for docker-mailserver and the true/false is for the chart, but if I was just trying to use the chart without "peeking inside" I don't know that I'd appreciate the difference.

**Comment by cfis** [comment]
Agreed. Not the true/false toggle has been removed, now its an env variable like all the other docker-mailserver ones (1/0)
