### ISSUE TITLE
DOVECOT_PASS_ATTR or DOVECOT_PASS_ATTRS

### ISSUE THREAD

**Issue by clayrisser** [docker-mailserver/docker-mailserver-helm#32]
Is it `DOVECOT_PASS_ATTR` or `DOVECOT_PASS_ATTRS`?

https://github.com/funkypenguin/helm-docker-mailserver/blob/61e733fe7f2e3e818de5385fbbb82559f6ad3d39/charts/docker-mailserver/templates/_upstream-env-variables.tpl#L98

docker mailserver uses `DOVECOT_PASS_ATTRS`.
https://github.com/tomav/docker-mailserver/blob/master/README.md#dovecot_pass_attrs

**Comment by funkypenguin** [comment]
I think you're right, it should be `DOVECOT_PASS_ATTRS`...

**Comment by cfis** [comment]
This env seems to have been removed from docker-mailserver and the chart. So closing the issue.
