### ISSUE TITLE
Rainloop setup screenshot missing

### ISSUE THREAD

**Issue by clayrisser** [docker-mailserver/docker-mailserver-helm#33]
Can the rainloop setup screenshot be added back?

https://github.com/funkypenguin/helm-docker-mailserver/blob/master/README.md#setup-rainloop

**Comment by cfis** [comment]
Since rainloop is no longer developed, it has been removed from the chart.

**Comment by clayrisser** [comment]
Is there another webmail solution the chart supports?

**Comment by cfis** [comment]
Currently no. Instead, you can install whatever webclient you like. For example, if you want to use Roudcube then there is a Helm chart here:

https://gitlab.com/MatthiasLohr/roundcube-helm-chart

Once installed, you then need to point Roudcube and the docker mailserver pod. Note if you are using TLS, you probably need to add a redirect in CoreDNS like this:

```
.:53 {
    ....
    rewrite name mail.example.com docker-mailserver.mail.svc.cluster.local
    kubernetes cluster.local in-addr.arpa ip6.arpa {
     ...
    }
    prometheus :9153
}
```

I'll add that to the docs.

**Comment by cfis** [comment]
FYI, the successor to RainLoop is SnappyMail - see https://snappymail.eu/. I don't see a Helm chart for it though. It is packaged as part of Nextcloud and Mailu if that is helpful.
