### ISSUE TITLE
Enable passing custom envs into the pod

### ISSUE THREAD

**Issue by clayrisser** [docker-mailserver/docker-mailserver-helm#34]
It would be nice if I could pass custom environment variables into the pod.

For example . . .

https://github.com/codejamninja/charts/blob/master/beta/mailserver/templates/releases/mailserver.yaml#L53

**Comment by cfis** [comment]
Yes, you can now. See https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#environment-variables
