### ISSUE TITLE
[suggestion] helm chart /config

### ISSUE THREAD

**Issue by cdeadspine** [docker-mailserver/docker-mailserver-helm#39]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Seems a bit inconsistent in how the chart's /config is used

**Describe the solution you'd like**
Perhaps include /config/postfix-main.cf (and other files) into ConfigMap, the same way postfix-accounts.cf is?

------------------------------
For instance, I am getting 
```
warning: do not list domain example.com in BOTH mydestination and virtual_mailbox_domains
postfix smtpd Recipient address rejected: User unknown in local recipient table
```

(not even sure this is the right fix, but by instinct)
Which leads me to try [changing mydestination](https://github.com/docker-mailserver/docker-mailserver/blob/55daef4820bc6566c7c8b78783223b4a92ff0b46/docs/content/config/troubleshooting/faq.md#can-i-use-nakedbare-domains-no-host-name)
```
in /config/postfix-main.cf (removing $myhostname, since "virtual" should be handling this maybe?)
mydestination = localhost.$mydomain, localhost
```

However, it appears the file /config/postfix-main.cf is not actually used for anything.
As proven by 
```
postconf -d
or
cat /etc/postfix/main.cf
in running pod
```
-----------------------------

(I don't understand enough of this stack to know yet, but it seems like that warning is hinting that $mydestination is not suppose to contain $myhostname, if we are using the virtual_mailbox_domains feature?)

**Comment by NicolasKarnick** [comment]
Hi, I stumbled across this problem, too. My entries in /config/postfix-main.cf dont get used. I solved this problem by deleting the demo mode stuff which had some if/else branches. After having a clearer configmap.yaml, my entries got used by the postfix pod.

``` release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-configs
data:
  postfix-main.cf: |
    mydestination = localhost localhost.$mydomain
  {{ if not .Values.spfTestsDisabled }}
    smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net{{ range .Values.rblRejectDomains }}, reject_rbl_client {{ . }}{{ end }}
  {{ end -}}
  {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}```

**Comment by cfis** [comment]
Hopefully this is no longer an issue, and demo mode has been removed. So closing this issue.
