### ISSUE TITLE
helm 3: Error: YAML parse error on docker-mailserver/templates/configmap.yaml: error converting YAML to JSON: yaml: line 61: could not find expected ':'

### ISSUE THREAD

**Issue by abh** [docker-mailserver/docker-mailserver-helm#4]
I have a `values.yaml` and ran

```
./setup.sh email add test@example.com password123
./setup.sh config dkim
 helm template -n mailserver mailserver -f values.yaml funkypenguin/docker-mailserver
```

and it errors out with

`Error: YAML parse error on docker-mailserver/templates/configmap.yaml: error converting YAML to JSON: yaml: line 61: could not find expected ':'`

If I remove

`  {{- (.Files.Glob "config/opendkim/*").AsConfig | nindent 2 }}`

from configmap.yaml then it works (except of course not adding the opendkim files to the configmap...). 

It also works if I remove `config/opendkim/keys/`, so I am guessing it's the Files.Glob ...AsConfig stuff that can't deal with subdirectories.

**Comment by abh** [comment]
oh, it's not reading my files at all but rather what's in the chart:

https://github.com/helm/helm/issues/3276

**Comment by abh** [comment]
My workaround is to have a local clone of the chart and then symlink'ing config/ from the directory where I have my local values.yaml.  It makes submitting changes here a real hassle though... :-)

**Comment by funkypenguin** [comment]
I have another solution which I use in a CI platform (where I can't just leave config files lying around).. 

I set:

```
configMap:
  useExisting: true

secret:
  useExisting: true
```

And then assemble the secret and configmap externally, and just inject them into the namespace. That way, helm doesn't interfere with them. You could just dump your current config/secrets out with `kubectl get <blah> -o yaml`, and then set the above values, and re-inject them "behind helm's back" ?

D

**Comment by abh** [comment]
Well, I think the only way it works in a "normal helm flow" is to "use existing", then.

The big missed opportunity having to do it this way (and I'm not sure there's a solution) is that the chart can't add a checksum of the config to an annotation.

I did that locally so the container automatically restarts when the config changes (which seems to be necessary at the moment).

Maybe have an option to put all the config files into values.yaml and then it's a documentation thing to explain how to load the files into a templates, make your local values.yaml a template and then run

```
helm template . --show-only values.yaml > values-generated.yaml
helm upgrade -n mailserver mail server -f values-generated.yaml funkypenguin/mailserver
```

when updating ...

**Comment by funkypenguin** [comment]
I agree it's a PITA right now. There's a tension between making the chart work smoothly for helm users, and maintaining compatibility with the way the docker image "wants" to work...

**Comment by nafets227** [comment]
Did you think about moving the parts executed by setup.sh into an init container?

One could have values.yaml like
```
pod:
  dockermailserver:
    initSettings:
      - email add test@example.com password123
      - config dkim
```

**Comment by cfis** [comment]
The latest version of the chart has updated the way configuration works - see https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#configuration.

Hopefully this is a better, more flexible solution.
