### ISSUE TITLE
Helm Repo

### ISSUE THREAD

**Issue by xavier83** [docker-mailserver/docker-mailserver-helm#44]
Where is this helm chart hosted for adding it to helm?

**Comment by dfoxg** [comment]
@funkypenguin are there plans to deploy this helm chart to any repo?

**Comment by funkypenguin** [comment]
Hmm, the README is a little out-of-date (as @rspier has also pointed out!), but there's a GitHub Action which publishes the chart repo as https://docker-mailserver.github.io/docker-mailserver-helm/

So it should be as simple as: `helm repo add docker-mailserver https://docker-mailserver.github.io/docker-mailserver-helm/`

**Comment by rspier** [comment]
I've updated pull request #48 to encompass this issue too.

**Comment by abh** [comment]
I added the GitHub based repository above to artifacthub (@funkypenguin , I added you to a new "org" for it -- you can kick me out).

https://artifacthub.io/packages/helm/docker-mailserver/docker-mailserver
