### ISSUE TITLE
PodSecurityPolicy is deprecated

### ISSUE THREAD

**Issue by khuedoan** [docker-mailserver/docker-mailserver-helm#49]
From Kubernetes docs:

> PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25. It has been replaced by [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/). For more information on the deprecation, see [PodSecurityPolicy Deprecation: Past, Present, and Future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/).

Related manifest: https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/templates/psp.yaml

I'm still deploying docker-mailserver to my cluster (using plain YAML), I'll try to create a PR after I got it working.

**Comment by mindrunner** [comment]
Did you make any progress on this?

**Comment by khuedoan** [comment]
Not yet, I was a bit busy at work.

**Comment by mindrunner** [comment]
Isn't that what you are supposed to do at work? :D

Does anyone know what happens when this chart is deployed w/o the psp?

**Comment by cfis** [comment]
`PodSecurityPolicy` has been removed from the chart. So closing this issue.
