### ISSUE TITLE
How to connect setup.sh with the remote pod?

### ISSUE THREAD

**Issue by winston0410** [docker-mailserver/docker-mailserver-helm#64]
I am following [the doc](https://artifacthub.io/packages/helm/docker-mailserver/docker-mailserver#create-update-delete-users) to deploy docker-mailserver on my k8s instance. I tried to run `./setup.sh` afterward, but it gives me an error:

```sh
base ❯ ./setup.sh donotreply@foo.com
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

--- \e[31m\e[1mUNCHECKED ERROR\e[0m
  - script    = ./setup.sh
  - function  = _main
  - command   = INFO=$(${CRI} ps --no-trunc --format "{{.Image}};{{.Names}}" --filter     label=org.opencontainers.image.title="docker-mailserver" | tail -1)
  - line      = 153
  - exit code = 1

This should not have happened. Please file a bug report.

--- \e[31m\e[1mUNCHECKED ERROR\e[0m
  - script    = ./setup.sh
  - function  = _main
  - command   = INFO=$(${CRI} ps --no-trunc --format "{{.Image}};{{.Names}}" --filter     label=org.opencontainers.image.title="docker-mailserver" | tail -1)
  - line      = 153
  - exit code = 1

This should not have happened. Please file a bug report.
```

so seems like it is trying to connect to the docker machine I am running in my desktop, instead of an instance in a remote location. How can I config the connection? I cannot find any doc mentioning this part.

**Comment by winston0410** [comment]
Reading the doc again, this script should be ran from host machine, does the host machine refer to a node in kubenetes? How can I use this script correctly?
https://docker-mailserver.github.io/docker-mailserver/edge/config/setup.sh/

**Comment by NicolasKarnick** [comment]
Could you resolve this issue?

**Comment by cfis** [comment]
The latest version of the chart no longer requires the use of `setup.sh`. Instead, use `setup`. See https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#getting-started
