### ISSUE TITLE
Template error in deployment of .Values.additionalVolumes

### ISSUE THREAD

**Issue by sspreitzer** [docker-mailserver/docker-mailserver-helm#68]
There seems to be an extranous `-` in `{{- toYaml` which seems to fail to render the template.

https://github.com/docker-mailserver/docker-mailserver-helm/blob/2782e399e7e9dbba93bfd77a57af4c3c087b5043/charts/docker-mailserver/templates/deployment.yaml#L59

```
Error: YAML parse error on docker-mailserver/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: did not find expected '-' indicator
```

The deployment template part of  `.Values.additionalVolumeMounts` is working.

**Comment by sspreitzer** [comment]
Also indent of 9 seems odd. Was this tested?

**Comment by cfis** [comment]
`additionalVolumeMounts` has been removed from the chart. So closing this issue.
