### ISSUE TITLE
Disabling demoMode breaks chart

### ISSUE THREAD

**Issue by jceb** [docker-mailserver/docker-mailserver-helm#71]
When I disable `demoMode.enable=false` I get the following error message:

```
Error: YAML parse error on docker-mailserver/templates/configmap.yaml: error converting YAML to JSON: yaml: line 63: did not find expected key

Use --debug flag to render out invalid YAML
```

The reason for the broken configuration is the inclusion of missing configuration files in the this instruction: https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/templates/configmap.yaml#L38

**Comment by MoJo2600** [comment]
I have the same issue. A beginner like me is not able to follow the instructions to set up this helm chart because it just breaks.

**Comment by cfis** [comment]
I ran into the same issue. demomode has been removed, so this is no longer an issue.
