### ISSUE TITLE
Dovecot locking issues on Kubernetes

### ISSUE THREAD

**Issue by colmryan3rdi** [docker-mailserver/docker-mailserver-helm#84]
Hi All 

Have managed to get a mailserver container running with ingress on my AKS instance but am receiving errors like the following when the IMAP client connects to the service:
------------------------------------------------
- imap([user@domain.net](mailto:user@domain.net))<7245><**************>: Error: Mailbox INBOX: Failed to autocreate mailbox: Internal error occurred. Refer to server log for more information. [2023-11-13 16:01:01]
 
- Nov 13 16:01:01 mail dovecot: imap([user@domain.net](mailto:user@domain.net))<7245><**************>: Error: Couldn't create mailbox list lock /var/mail/domain.net/{user}/mailboxes.lock: file_create_locked(/var/mail/domain.net/user/mailboxes.lock) failed: link(/var/mail/domain.net/user/mailboxes.lockcf866fd722cae35e, /var/mail/domain.net/user/mailboxes.lock) failed: Operation not supported

- Nov 13 16:01:01 mail dovecot: imap([user@domain.net](mailto:user@domain.net))<7245><**************>: Error: Mailbox Drafts: Failed to autocreate mailbox: Internal error occurred. Refer to server log for more information. [2023-11-13 16:01:01]
-------------------------------------------------
I am using SMB 3.0 mount with the following parameters for the mail data directory
:
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - username={{ .Values.userName }}
  - password={{ .Values.storageAccountKey }}
  - mfsymlinks
  - nobrl
  - vers=3.0
  - serverino
----------------------------------------------------------
Is there by any chance a requirement that dovecot needs to have an NFS volume mount and this might be what's causing the issue? I am in a little uncharted territory here.

Any input would be most welcome. I'd love to get this up and running for my deployment.

**Comment by cfis** [comment]
Could you try the latest chart. By default config files are stored on a Volume which would be mounted as `ReadWriteOnce`.

**Comment by cfis** [comment]
Going to close this - reopen if you still have issues with the new chart.
