### ISSUE TITLE
fix: `poorMansK8sLb`

### ISSUE THREAD

**Issue by jjangga0214** [docker-mailserver/docker-mailserver-helm#86]
Hi!

It seems `poorMansK8sLb` does not exist from *`values.yaml`*, but README.md and *`NOTE.txt`* refers to it.

Is it a mistake?

Thanks!

**Comment by funkypenguin** [comment]
https://github.com/funkypenguin/poor-mans-k8s-lb was originally supported by the chart, but I think we removed it some time ago (it's also unmaintained and unloved). I suspect it was just not properly removed from `README.md` and `NOTE.txt` :)

**Comment by cfis** [comment]
It is now removed. Final remenants in https://github.com/docker-mailserver/docker-mailserver-helm/pull/91
