### ISSUE TITLE
[Feature Request] Clarifying info for LDAP deployments

### ISSUE THREAD

**Issue by senatormailman** [docker-mailserver/docker-mailserver-helm#87]
**Motivation**
I am confused as how the underlying mechanisms handle configuration. I am using LDAP and I was reviewing the documentation about how to configure docker-mailserver that way. I wanted to use a secret to store this data but I notice in the helm chart's doc, there's not much detail about how to do that. I think based on what I am seeing in the `secret.yaml` template, if I just make my own secret and name it the helm chart (appended with `-secrets`) will cause that to work?

**Describe the solution you'd like**
I think for using secrets and configmaps, having a default and an expectation as to how to name those secrets/configmaps will help.

**Describe alternatives you've considered**
I have tried to just create a secret by hand. I have also tried to just leverage the pre-generated secret. Creating it by hand made me worried that I configured it wrong, the pre-generated secret basically confirmed that for me.

**Additional context**
I am running Rancher via K3s on x86_64 architecture. When I tried to make a secret, I created a key-value pair. That's why I feel that my secret was incorrect. I noticed that the pre-generated secret was just an RSA private key.

**Comment by cfis** [comment]
Version 3.0.0 of the chart has redone the way configuration is handled. See https://github.com/docker-mailserver/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#configuration

See if that helps. If you need additional help please reopen this ticket.
